"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Overlay from "@/components/Overlay";
import Sidebar from "@/components/Sidebar";
import { useState } from "react";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Reviews",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [isOpen, setIsOpen] = useState(false);
  //dark:bg-slate-900 bg-slate-50 dark:border-slate-600  transition-colors duration-300
  return (
    <html lang="en">
      <body className={`${inter.className}  min-h-screen h-screen relative flex flex-col `}>
        <header className="">
          <Navbar isOpen={isOpen} setIsOpen={setIsOpen} />
          <Overlay isOpen={isOpen} setIsOpen={setIsOpen} />
          <Sidebar isOpen={isOpen} setIsOpen={setIsOpen} />
        </header>
        {/* h-[calc(100%-3.5rem-3.5rem)] */}
        {/* px-6 py-2 lg:py-6  */}
        <main className=" dark:bg-slate-900 bg-slate-50 dark:text-gray-400 transition-colors duration-300 w-full h-full lg:w-[calc(100%-20rem)] lg:translate-x-80 overflow-auto">
          {children}
        </main>
        <footer className="lg:w-[calc(100%-20rem)] lg:translate-x-80">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
